version: "3"

services:
  db:
    image: postgres:11-alpine
    container_name: db.tracker
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: tracker
      POSTGRES_PASSWORD: tracker
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    networks:
      - private

networks:
  private:
    driver: bridge
